[52] - Delete account
U6D5T4/Auctionify pull request #103
Opened 2024-01-24 11:23 UTC by khasanrashidov

2024-01-31 12:34 UTC, SaidganiUsm approved these changes
Checked

2024-02-03 12:55 UTC, TsvirkoNikita requested changes

2024-02-03 12:55 UTC, TsvirkoNikita commented on src/Auctionify.Application/Features/Users/Commands/Delete/DeleteUserCommandValidator.cs
> +			ClassLevelCascadeMode = CascadeMode.Stop;
You have only one rule in validator and looks like to set the ClassLevelCascadeMode not needed

2024-02-03 12:55 UTC, TsvirkoNikita commented on src/Auctionify.Application/Features/Users/Commands/Delete/DeleteUserCommandValidator.cs
> +				.Cascade(CascadeMode.Stop)
Same here

2024-02-03 12:55 UTC, TsvirkoNikita commented on src/Auctionify.Application/Features/Users/Commands/Delete/DeleteUserCommandValidator.cs
> +							foreach (var bid in bids)
Retrieving each lot and lot status in separate request, too expensive, besides there is no need to get this data into memory. Please update the query above so that it determines the presence of lots in active status at the database level

2024-02-03 12:55 UTC, TsvirkoNikita commented on src/Auctionify.Application/Features/Users/Commands/Delete/DeleteUserCommandValidator.cs
> +							foreach (var lot in lots)
Same for this foreach, check my comment above

2024-02-03 13:22 UTC, khasanrashidov commented on src/Auctionify.Application/Features/Users/Commands/Delete/DeleteUserCommandValidator.cs
> +			ClassLevelCascadeMode = CascadeMode.Stop;
resolved

2024-02-03 13:22 UTC, khasanrashidov commented on src/Auctionify.Application/Features/Users/Commands/Delete/DeleteUserCommandValidator.cs
> +				.Cascade(CascadeMode.Stop)
resolved

2024-02-03 13:44 UTC, khasanrashidov commented on src/Auctionify.Application/Features/Users/Commands/Delete/DeleteUserCommandValidator.cs
> +							foreach (var bid in bids)
resolved

2024-02-03 13:44 UTC, khasanrashidov commented on src/Auctionify.Application/Features/Users/Commands/Delete/DeleteUserCommandValidator.cs
> +							foreach (var lot in lots)
resolved

2024-02-03 14:20 UTC, khasanrashidov commented
corrected all fix/change requests

2024-02-03 16:19 UTC, TsvirkoNikita requested changes

2024-02-03 16:19 UTC, TsvirkoNikita commented on src/Auctionify.Application/Features/Users/Commands/Delete/DeleteUserCommandValidator.cs
> +							return bids.All(
It's better, but you load all bids with related data into memory anyway. You can use All EF extension method as part of your query and get just bool result from db instead.

2024-02-03 16:19 UTC, TsvirkoNikita commented on src/Auctionify.Application/Features/Users/Commands/Delete/DeleteUserCommandValidator.cs
> +							return lots.All(
Same for this one

2024-02-03 17:05 UTC, khasanrashidov commented on src/Auctionify.Application/Features/Users/Commands/Delete/DeleteUserCommandValidator.cs
> +							return bids.All(
Should I use All as a part of my query? or what do you think of AnyAsync?

2024-02-03 17:12 UTC, khasanrashidov commented on src/Auctionify.Application/Features/Users/Commands/Delete/DeleteUserCommandValidator.cs
> +							return bids.All(
okay, got you) I will do it

2024-02-03 18:12 UTC, khasanrashidov commented on src/Auctionify.Application/Features/Users/Commands/Delete/DeleteUserCommandValidator.cs
> +							return lots.All(
I used any async:
![image](https://github.com/U6D5T4/Auctionify/assets/89701590/c56ca3e7-0b92-4ac7-a3f3-3a90d389e65f)

2024-02-03 18:14 UTC, khasanrashidov commented on src/Auctionify.Application/Features/Users/Commands/Delete/DeleteUserCommandValidator.cs
> +							return bids.All(
Thank you for noticing such things, these suggestions really do help and make sense!))

2024-02-03 18:14 UTC, khasanrashidov commented on src/Auctionify.Application/Features/Users/Commands/Delete/DeleteUserCommandValidator.cs
> +							return lots.All(
I guess that makes the retrieval more efficient)

2024-02-04 07:18 UTC, SaidganiUsm approved these changes

2024-02-04 09:26 UTC, merged