[164] Update sender for confirmation emails
U6D5T4/Auctionify pull request #106
Opened 2024-01-25 19:30 UTC by SaidganiUsm

Where
[NL-164 Update sender for confirmation emails](https://jjbcapital.atlassian.net/browse/NL-164)

What
Switching to smtp with new email address

Affected Area
Auctionify.Infrastructure
Auctionify.API

PR Checklist
Build

 Build Succeeded
Unit Tests

[x] All 84 Tests Passed, 0 Ignored, 0 Failed

2024-01-28 19:44 UTC, otash8110 submitted a review, later dismissed

2024-01-29 08:12 UTC, otash8110 approved these changes

2024-01-29 09:39 UTC, TsvirkoNikita requested changes

2024-01-29 09:39 UTC, TsvirkoNikita commented on src/Auctionify.API/appsettings.Development.json
Please apply those changes to appsettings.dev and don't forget to update Application settings in Azure to apply those settings too

2024-01-29 15:59 UTC, khasanrashidov approved these changes

2024-01-29 15:59 UTC, merged