[155] - Lot is active after passed end date
U6D5T4/Auctionify pull request #107
Opened 2024-01-28 19:43 UTC by otash8110

### Where

[NL-155 Lot is active after passed end date](https://jjbcapital.atlassian.net/browse/NL-155)

### What

Avoid incorrect statuses for lots

### How

Implement global Backgroun job which is triggered every 5 minutes and iterates over all lots in the system.  If lot's status is wrong based on various factors it changes status to the correct one

### Affected Area

Auctionify.Application.Scheduler
Auctionify.Application.Common

### PR Checklist

_Build_

- [x] Build Succeeded

_Unit Tests_

- [x] X Tests Passed, Y Ignored, Z Failed

2024-01-29 08:57 UTC, khasanrashidov submitted a review, later dismissed

2024-01-29 16:46 UTC, SevenDart requested changes

2024-01-29 16:46 UTC, SevenDart commented on src/Auctionify.Application/Scheduler/JobSchedulerService.cs
> +            return $"upcoming-active-{lotId}";
you should use constants from the top of the file instead of strings, same for FormFinishLotJobKey and FromDeleteDraftLotJobKey
Moreover, you can combine methods into one, using as the first parameter name of the group, as the second - lot id. Something like FormJobKey(string jobName, int lotId)

2024-01-31 10:49 UTC, khasanrashidov approved these changes, later dismissed

2024-02-07 08:33 UTC, khasanrashidov approved these changes

2024-02-07 08:35 UTC, SaidganiUsm approved these changes

2024-02-07 13:47 UTC, SevenDart approved these changes

2024-02-08 07:09 UTC, merged