[163] - User can't create a seller account if he has a buyer account using the same e-mail. Allow it
U6D5T4/Auctionify pull request #108
Opened 2024-01-31 12:42 UTC by khasanrashidov

2024-02-11 08:34 UTC, otash8110 submitted a review, later dismissed

2024-02-12 03:53 UTC, khasanrashidov commented
@TsvirkoNikita you can review, @otash8110 Otabek reviewed this pr and approved (but the merge-base changed after approval, yeah, which can be easily solved by switching to/back to comparing branch)))

![image](https://github.com/U6D5T4/Auctionify/assets/89701590/97e3a681-d75f-46f7-b15e-d97f1d7a1ba4)

2024-02-17 08:25 UTC, otash8110 submitted a review, later dismissed

2024-02-17 12:21 UTC, TsvirkoNikita requested changes

2024-02-17 12:21 UTC, TsvirkoNikita commented on src/Auctionify.Infrastructure/Identity/IdentityService.cs
> +			if (userRoles.Any())
Inside foreach you get same role from db multiple times. You can simplify this section:

```
var userRole = await _roleManager.FindByNameAsync(role);
if (userRoles.Any(ur => ur.RoleId == userRole!.Id))
{
    var token = await GenerateJWTTokenWithUserClaimsAsync(user, role);

    token.Role = role;
    token.UserId = user.Id;

    return new LoginResponse { IsSuccess = true, Result = token };
}
```

2024-02-17 12:21 UTC, TsvirkoNikita commented on src/Auctionify.Infrastructure/Identity/IdentityService.cs
> +			if (userRoles.Any())
Similar section as above, please, refactor it

2024-02-17 15:08 UTC, khasanrashidov commented on src/Auctionify.Infrastructure/Identity/IdentityService.cs
> +			if (userRoles.Any())
Yes, thank you for noticing) I will refactor it)

2024-02-17 15:11 UTC, khasanrashidov commented on src/Auctionify.Infrastructure/Identity/IdentityService.cs
> +			if (userRoles.Any())
refactored it

2024-02-17 15:11 UTC, khasanrashidov commented
fixed specified issues in pr comments

2024-02-17 15:20 UTC, TsvirkoNikita submitted a review, later dismissed

2024-02-17 15:39 UTC, SaidganiUsm approved these changes

2024-02-17 15:41 UTC, TsvirkoNikita approved these changes

2024-02-17 15:56 UTC, merged