[161] Location data recommendations and validation. Saving latitude a…
U6D5T4/Auctionify pull request #109
Opened 2024-02-02 14:41 UTC by SaidganiUsm

### Where

[NL-161 Update location inputs to process only correct cities/countries etc](https://jjbcapital.atlassian.net/browse/NL-161)

### What

Autofilling address line in the lot creation stage, fetching latitude and longitude of a provided address, saving this geolocation, and using it in lot profile for map.

### How

I used Goeocode API from Google MapsApi and used a leaflet package for showing maps based on latitude and longitude.

### Affected Area

Auctionify.API
Auctionify.Application
Auctionify.Entitie
Auctionify.Infrastructure

### PR Checklist

_Build_

- [x] Build Succeeded

_Unit Tests_

- [x] X Tests Passed, Y Ignored, Z Failed

2024-02-12 03:51 UTC, khasanrashidov submitted a review, later dismissed

2024-02-12 10:34 UTC, TsvirkoNikita requested changes
- When editing a lot, lot update request fails without any error message for user. The reason for the error is missing Latitude and Longitude fields in the request:
![image](https://github.com/U6D5T4/Auctionify/assets/35694505/b96aa81b-68c4-4342-a16e-a1882558d06b)
Fix this bug and fix popup with any errors showing.
- Another issue related to Country and City fields. You still can put anything to it after you enter Address field:
![image](https://github.com/U6D5T4/Auctionify/assets/35694505/7976c0b1-37d0-4dcf-a4c0-d7ff7de17946)
I suggest making these fields disabled as they are filled in automatically after entering the address anyway

2024-02-12 10:34 UTC, TsvirkoNikita commented on src/Auctionify.Application/ConfigureServices.cs
Remove unused usings

2024-02-14 09:39 UTC, TsvirkoNikita requested changes
- If scroll page down before open location popup, Google suggestions displaying too up
- Country and City inputs disabled for input, but still looks like active. It should be displayed as disabled with gray background
![image](https://github.com/U6D5T4/Auctionify/assets/35694505/3a24984e-e382-4541-9983-c3670537bc27)

2024-02-18 17:03 UTC, SaidganiUsm commented
Unfortunately, it was not possible to correct the location of the location recommendations element

2024-02-20 09:26 UTC, TsvirkoNikita approved these changes

2024-02-20 16:05 UTC, khasanrashidov approved these changes

2024-02-20 16:12 UTC, merged