[27] - Create messages page
U6D5T4/Auctionify pull request #110
Opened 2024-02-04 09:46 UTC by otash8110

### Where

[NL-27 Create messages page](https://jjbcapital.atlassian.net/browse/NL-27)

### What

Implement chat functionality and page on frontend

### How

Using updates provided on backend side, create frontend layout for chats and messaging. this branch populates 1 conversatio between seller@localhost.com and buyer@localhost.com for testing purposes. All real conversations will be created by background job workers when lot statuses are changed to sold

### Affected Area

Auctionify.API.ClientApp
Auctionify.Application

### PR Checklist

_Build_

- [x] Build Succeeded

_Unit Tests_

- [x] 102 passed, 0 Ignored, 0 Failed

2024-02-05 08:41 UTC, khasanrashidov commented on src/Auctionify.API/ClientApp/src/app/components/general/chat/conversation-window/conversation-window.component.ts
> +        console.log(el, this.firstUnreadId);
Do we need to log this info into console?

2024-02-05 08:41 UTC, khasanrashidov commented on src/Auctionify.API/ClientApp/src/app/components/general/chat/conversation-window/conversation-window.component.ts
> +                    console.log('UNREAD');
do we need it here too?

2024-02-05 08:41 UTC, khasanrashidov commented on src/Auctionify.API/ClientApp/src/app/components/general/chat/conversation-window/conversation-window.component.ts
> +            console.log(event.isIntersecting, event.isRead);
what about here?

2024-02-05 08:54 UTC, khasanrashidov commented
When there are no conversations (which means there are no chats), I think the following should be shown

![image](https://github.com/U6D5T4/Auctionify/assets/89701590/e222d84e-340f-4dc6-ac62-c59d9c91548c)

What we have now (the case we don't have conversations):

![image](https://github.com/U6D5T4/Auctionify/assets/89701590/483373d7-d9ec-4129-872d-984316184007)

2024-02-05 08:57 UTC, khasanrashidov commented on src/Auctionify.API/ClientApp/src/app/components/general/chat/chat-page/chat-page.component.ts
> +            return 'chat-width-seller';
I would assign them into constants and return them

2024-02-05 08:58 UTC, khasanrashidov commented on src/Auctionify.API/ClientApp/src/app/components/general/chat/conversation-window/conversation-window.component.ts
> +        } else return 'other';
is it better to assign them into constants?

2024-02-05 09:00 UTC, khasanrashidov commented on src/Auctionify.API/ClientApp/src/app/components/general/chat/conversation-window/conversation-window.component.ts
> +            if (percent < 97.6) this.isScrolledUp = true;
As I understand, 97.6 is the threshold for the scroll to be considered at the bottom, right?

2024-02-09 08:32 UTC, khasanrashidov approved these changes

2024-02-15 07:41 UTC, Muhammad-gf requested changes

2024-02-15 07:41 UTC, Muhammad-gf commented on src/Auctionify.API/ClientApp/src/app/components/general/chat/chats/chats.component.ts
> +    OnInit,
You didn't use ngOnInit. You can remove it.

2024-02-15 07:41 UTC, Muhammad-gf commented on src/Auctionify.API/ClientApp/src/app/components/general/chat/chat-page/chat-page.component.ts
> +    ElementRef,
Remove 'ElementRef, ViewChild, ChatsComponent'.

2024-02-16 16:14 UTC, khasanrashidov submitted a review, later dismissed

2024-02-19 09:20 UTC, Muhammad-gf approved these changes

2024-02-19 10:01 UTC, SaidganiUsm approved these changes

2024-02-19 10:02 UTC, khasanrashidov approved these changes

2024-02-19 10:14 UTC, merged