[49] - PRO subscription(seller)
U6D5T4/Auctionify pull request #115
Opened 2024-02-13 07:05 UTC by otash8110

### Where

[[49] - PRO subscription(seller)](https://jjbcapital.atlassian.net/browse/NL-49)

### What

Implement functionality for upgrading to PRO subscribtion and cancel it

### How

Implementation covered frontend and backend parts along with testing. Base markup pages are created for future implementation based on design

### Affected Area

Auctionify.API.Controllers
Auctionify.API.ClientApp
Auctionify.Application.Features
Auctionify.Infrastructure

### PR Checklist

_Build_

- [x] Build Succeeded

_Unit Tests_

- [x] X Tests Passed, Y Ignored, Z Failed

2024-02-13 12:48 UTC, khasanrashidov requested changes

2024-02-13 12:48 UTC, khasanrashidov commented on src/Auctionify.Application/Features/Subscriptions/Commands/CreateProSubscriptionCommand.cs
> +				throw;
"catch" clauses should do more than rethrow

Why is this an issue?

A catch clause that only rethrows the caught exception has the same effect as omitting the catch altogether and letting it bubble up automatically.

Such clauses should either be removed or populated with the appropriate logic.

Еither remove it (try/catch), or just log it, i.e. populate catch part somehow))

Example:

```Noncompliant code:```

```
string s = "";
try
{
  s = File.ReadAllText(fileName);
}
catch (Exception e)  // Noncompliant
{
  throw;
}
```

solution would be either:

1) just removing the try catch:
string s = File.ReadAllText(fileName);

**or**
2) e.g. logging it:

string s = "";
try
{
  s = File.ReadAllText(fileName);
}
catch (Exception e)
{
  logger.LogError(e);
  throw;
}

2024-02-13 12:48 UTC, khasanrashidov commented on src/Auctionify.Application/Features/Subscriptions/Commands/DeleteProSubscription/DeleteProSubscriptionCommand.cs
> +                throw new Exception("User does not have any subscriptions");
same here, look in the previous comment about throwing exception

2024-02-13 12:48 UTC, khasanrashidov commented on src/Auctionify.Core/Enums/SubscriptionTypeEnum.cs
> +    public enum SubscriptionTypeEnum
Enumeration type names should not have "Flags" or "Enum" suffixes.

Why is this an issue?

The information that an enumeration type is actually an enumeration or a set of flags should not be duplicated in its name.

2024-02-13 13:19 UTC, khasanrashidov approved these changes, later dismissed

2024-02-17 13:53 UTC, khasanrashidov submitted a review, later dismissed

2024-02-17 15:05 UTC, TsvirkoNikita requested changes

2024-02-18 19:52 UTC, merged