[172] Implement report generating functionality
U6D5T4/Auctionify pull request #118
Opened 2024-02-14 17:35 UTC by SaidganiUsm

### Where

[172] - Implement report generating functionality](https://jjbcapital.atlassian.net/browse/NL-172)

### What

Implement report generation service for premium subscribers

### How

Implemented new functionality for generation report for sellers with premium subscription. Used ClosedXml and QuestPDF for generation process.

### Affected Area

Auctionify.API.Controllers
Auctionify.API.ClientApp
Auctionify.Application.Features
Auctionify.Infrastructure

### PR Checklist

_Build_

- [x] Build Succeeded

_Unit Tests_

- [x] X Tests Passed, Y Ignored, Z Failed

2024-02-14 17:54 UTC, khasanrashidov requested changes
Look my thread of request changes)

2024-02-14 17:54 UTC, khasanrashidov commented on src/Auctionify.API/Controllers/ReportsController.cs
> +		public async Task<IActionResult> GetReport(int monthsDuration, string reportType)
Did you consider using [FromQuery][Required] here for arguments of your endpoint? If so, why would you not use it?

2024-02-14 17:54 UTC, khasanrashidov commented on src/Auctionify.API/Controllers/ReportsController.cs
> +				return NotFound("Report could not be generated.");
That is actually bad request)

2024-02-14 17:54 UTC, khasanrashidov commented on src/Auctionify.Application/Features/Reports/Query/Generate/GenerateReportQuery.cs
> +			case "PDF":
You have your enum with return file types, why did not you consider using it?

2024-02-14 17:54 UTC, khasanrashidov commented on src/Auctionify.Application/Features/Reports/Query/Generate/GenerateReportQuery.cs
> +			case "XLSX":
here too

2024-02-14 17:54 UTC, khasanrashidov commented on src/Auctionify.Core/Enums/ReportType.cs
> +	Unknown
what is Unknown for?

2024-02-16 22:49 UTC, khasanrashidov requested changes

2024-02-16 22:49 UTC, khasanrashidov commented on src/Auctionify.API/Controllers/ReportsController.cs
> +		public async Task<IActionResult> GetReport([FromBody]int monthsDuration, ReportType reportType)
See, when I meant using [FromQuery][Required], it would not accept in empty body (in your case, you can check the swagger). Because it would make it required. Plus it would make the api call neat, compare:

 **/reports?monthsDuration=3&reportType=PDF** 

with your call.

So, in my opinion this is preferable:

```
[FromQuery][Required] int monthsDuration,
[FromQuery][Required] ReportType reportType
```

If you want to make the default report type specified (e.g. let's say PDF is default), and want to make api call like that:

 **/reports?monthsDuration=3** 

and you want it to return PDF by default you can make it, like following:

```
[FromQuery][Required] int monthsDuration,
[FromQuery] ReportType reportType = ReportType.PDF

```

By the way, add check for the cases where you have 0 or negative months, and return BadRequest, just use the following:

```
			// if monthsDuration is less than 1 or equal to 0, return BadRequest
			if (monthsDuration < 1)
			{
				return BadRequest("Months duration must be greater than 0");
			}
```

2024-02-18 17:00 UTC, khasanrashidov submitted a review, later dismissed

2024-02-19 09:41 UTC, TsvirkoNikita requested changes
If I try to get a report without any sold items for requested period, endpoint broken with 500 error when trying to set the TotalSoldItemsValue property

2024-02-19 09:41 UTC, TsvirkoNikita commented on src/Auctionify.Application/Common/Interfaces/IReportService.cs
> +	public interface IXlsxReportGeneratorService : ICoreReportGeneratorService { }
What the reason to have two different interfaces without any specific methods?

2024-02-20 09:06 UTC, TsvirkoNikita requested changes
You should never update a migration that has already been applied somewhere, it is always better to add a new one

2024-02-21 08:44 UTC, TsvirkoNikita requested changes
- Report should contain a table with data for each month, not only result values
- Add data date range into report

2024-02-22 10:53 UTC, TsvirkoNikita requested changes

2024-02-22 10:53 UTC, TsvirkoNikita commented on src/Auctionify.Infrastructure/Services/ReportGeneratorService.cs
> +						column.Item().Text($"User: {user.FirstName} {user.LastName}",
You use obsolete overload, instead use this overload and fix other cases:
`column.Item().Text($"User: {user.FirstName} {user.LastName}").Bold().FontSize(16);`

2024-02-22 10:53 UTC, TsvirkoNikita commented on src/Auctionify.Infrastructure/Services/ReportGeneratorService.cs
> +		public async Task<byte[]> GenerateReportAsync(ReportData reportData, User user, ReportType format)
It's a synchronous method, there is no point in using it as an async method, so change it to sync

2024-02-23 06:39 UTC, TsvirkoNikita requested changes

2024-02-23 06:39 UTC, TsvirkoNikita commented on src/Auctionify.Application/Common/Interfaces/IReportService.cs
> +		byte[] GenerateReportAsync(ReportData reportData, User user, ReportType format);
Fix method name

2024-02-23 09:44 UTC, TsvirkoNikita submitted a review, later dismissed

2024-02-24 17:59 UTC, khasanrashidov approved these changes

2024-02-25 07:50 UTC, otash8110 approved these changes

2024-02-25 07:58 UTC, merged