[83] - NL-83 Create lot/auction (Backend)
U6D5T4/Auctionify pull request #12
Opened 2023-10-13 07:48 UTC by otash8110

### Where

[NL-83 Create lot/auction (Backend)](https://jjbcapital.atlassian.net/browse/NL-83)

### What

Implement functionality for creating Lots available only to sellers.

### How

Implemented within CQRS command and command-handler with usage of DTOs and FluentValidation which validates business properites of command. Also includes some logic for draft creation.

ICurrentUserService is added for future user validations/usages of User entity in business logic

Includes a vast amount of refactoring taken from branch dev_89

### Affected Area

Auctionify.API
Auctionify.Core
Auctionify.Application
Auctionify.Infrastructure

### PR Checklist

_Build_

- [x] Build Succeeded

2023-10-13 16:42 UTC, TsvirkoNikita requested changes

2023-10-13 16:42 UTC, TsvirkoNikita commented on src/Auctionify.API/Controllers/LotsController.cs
> -        public async Task<IActionResult> GetAll()
Why are you removing the GetAll endpoint?

2023-10-13 16:42 UTC, TsvirkoNikita commented on src/Auctionify.API/Controllers/LotsController.cs
> +		public async Task<IActionResult> Create(CreateLotCommand createLotCommand)
To handle files correctly, add [FromForm] attribute to createLotCommand parameter

2023-10-13 16:42 UTC, TsvirkoNikita commented on src/Auctionify.Core/Entities/Lot.cs
> +		public int? CurrencyId { get; set; }
What is the reason to change Category and Currency as not required? Is it for draft lot?

2023-10-13 16:42 UTC, TsvirkoNikita commented on src/Auctionify.Application/Features/Lots/Commands/Create/CreateLotCommand.cs
> +        public LocationDto Location { get; set; }
You need to declare separate Location related properties instead of using Location object here. Because if you pass object, you need to pass all their properties, include Id

2023-10-13 16:42 UTC, TsvirkoNikita commented on src/Auctionify.Application/Common/Behaviours/ValidationBehaviour.cs
> +                    throw new ValidationException(failures);
With throwing ValidationException your endpoints will respond with 500 error if they catch validation errors. You should update your ExceptionHandlerMiddleware to handle this exception with corresponding status code.

2023-10-13 16:42 UTC, TsvirkoNikita commented on src/Auctionify.Application/Features/Lots/Commands/Create/CreateLotCommandValidator.cs
> +                .When(l => l.EndDate == DateTime.MinValue ? false : true)
Using a ternary operator does not make sense here

2023-10-13 18:54 UTC, otash8110 commented on src/Auctionify.API/Controllers/LotsController.cs
> -        public async Task<IActionResult> GetAll()
It was a mistake taken from previous updates. Fixed and added again

2023-10-13 18:56 UTC, otash8110 commented on src/Auctionify.Core/Entities/Lot.cs
> +		public int? CurrencyId { get; set; }
Yes it is for draft lot. When creating a draft anything can be null except title and description

2023-10-16 07:30 UTC, TsvirkoNikita requested changes

2023-10-16 07:30 UTC, TsvirkoNikita commented on src/Auctionify.API/Controllers/LotsController.cs
> +		[Authorize(Roles = "Seller")]
Configure the Swagger to use your JWT tokens in requests. Check this example - https://www.freecodespot.com/blog/use-jwt-bearer-authorization-in-swagger/

2023-10-16 08:30 UTC, SevenDart commented on src/Auctionify.API/Middlewares/CustomExceptionHandlerMiddleware.cs
It is okay to use your own exceptionHandlerMiddleware, I just wanted to share, that Microsoft is offering their own middleware creator for exception handling: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-7.0#exception-handler-lambda.
I don't think you need to change anything, but if you will need to provide more information about exception, you can use IExceptionHandlerPathFeature like exampled in the code of that page

2023-10-16 11:29 UTC, TsvirkoNikita requested changes

2023-10-16 11:29 UTC, TsvirkoNikita commented on src/Auctionify.Application/Features/Lots/Profiles/MappingProfiles.cs
> -            CreateMap<Lot, GetAllLotsResponse>().ReverseMap();
Return this mapping, without it the GetAllLots endpoint is returning mapping exception now

2023-10-17 07:11 UTC, merged