[179, 182, 180, 181, 178] bug fixes
U6D5T4/Auctionify pull request #121
Opened 2024-02-21 12:18 UTC by khasanrashidov

### Where

[NL-179 Sign Up flow - unclear error message](https://jjbcapital.atlassian.net/browse/NL-179)
[NL-182 Add lot profile link in first message sent from seller (automatic message)](https://jjbcapital.atlassian.net/browse/NL-182)
[NL-180 View lot profile (buyer) - disable 'Place a bid" button in case the lot is not active](https://jjbcapital.atlassian.net/browse/NL-180)
[NL-181 Conversations are not sorted after message sent/received](https://jjbcapital.atlassian.net/browse/NL-181)
[NL-178 Add a time display for sent messages](https://jjbcapital.atlassian.net/browse/NL-178)

** NOTE **
In 178 I added time display, the time zone issue will be solved by Saidgani in another ticked.

### What

The goal of the changes is to fix all of the specified issues.

### How

Every issue has been resolved.

### Affected Area

Auctionify.API.ClientApp
Auctionify.Application

### PR Checklist

_Build_

- [x] Build Succeeded

_Unit Tests_

- [x] All Tests Passed, 0 Ignored, 0 Failed

2024-02-21 13:06 UTC, SaidganiUsm approved these changes

2024-02-21 17:40 UTC, khasanrashidov commented
resolved, finished

2024-02-21 17:42 UTC, SaidganiUsm approved these changes

2024-02-22 13:02 UTC, TsvirkoNikita requested changes

2024-02-22 13:02 UTC, TsvirkoNikita commented on src/Auctionify.API/ClientApp/src/app/components/general/chat/chat-item/chat-item.component.html
> +                    {{ messageDate | date : 'HH:mm' }}
Make sense to add also date here

2024-02-22 13:04 UTC, khasanrashidov commented on src/Auctionify.Application/Scheduler/Jobs/FinishLotJob.cs
> +							+ $"My name is {lot.Seller.FirstName} {lot.Seller.LastName} and I am the seller of the lot with id: {lotId}. "
Right!) will fix all issues

2024-02-22 13:43 UTC, khasanrashidov commented on src/Auctionify.API/ClientApp/src/app/components/general/lot-profile/lot-profile.component.html
> +                                lotData.lotStatus.name !== 'Active'
fixed

2024-02-23 06:44 UTC, TsvirkoNikita approved these changes

2024-02-23 06:50 UTC, merged