[176] Account creation flow fix
U6D5T4/Auctionify pull request #124
Opened 2024-02-24 18:38 UTC by SaidganiUsm

### Where

[176] - Account creation flow fix](https://jjbcapital.atlassian.net/browse/NL-176)

### What

First and last name fields added in front end signup page

### How

First and last name fields added in front end signup page

### Affected Area

Auctionify.API.ClientApp
Auctionify.Infrastructure

### PR Checklist

_Build_

- [x] Build Succeeded

_Unit Tests_

- [x] X Tests Passed, Y Ignored, Z Failed

2024-02-24 18:40 UTC, khasanrashidov approved these changes

2024-02-26 07:48 UTC, TsvirkoNikita requested changes
Endpoint errors are not displayed:
![image](https://github.com/U6D5T4/Auctionify/assets/35694505/8dc770b0-afcd-456b-84b3-52a93ec37733)
![image](https://github.com/U6D5T4/Auctionify/assets/35694505/0baeed89-7e80-49dd-b5cf-9347bfd8112d)

2024-02-26 07:48 UTC, TsvirkoNikita commented on src/Auctionify.Application/Common/Models/Account/RegisterViewModel.cs
> +        //[Compare("Password", ErrorMessage = "Passwords do not match.")]
Remove commented code if you not need it

2024-02-27 03:13 UTC, khasanrashidov submitted a review, later dismissed

2024-02-27 07:13 UTC, TsvirkoNikita requested changes
Errors still not showing:
![image](https://github.com/U6D5T4/Auctionify/assets/35694505/30a2c73c-bdf9-4cf2-a944-48096b86a1b0)

2024-02-28 07:22 UTC, TsvirkoNikita approved these changes

2024-02-28 09:34 UTC, khasanrashidov approved these changes

2024-02-28 09:47 UTC, merged