[34] - Implement analytics page
U6D5T4/Auctionify pull request #126
Opened 2024-02-26 17:50 UTC by khasanrashidov

### Where

[NL-34 Implement analytics page](https://jjbcapital.atlassian.net/browse/NL-34)

### What

The goal is to implement the analytics page (with all stats, graphs emphasized in the ticked), when seller subscribes pro subscription.

### How

Implemented all specified stats in the ticket.

some sample photos:

![image_2024-02-26_22-20-07](https://github.com/U6D5T4/Auctionify/assets/89701590/3ee4d197-83f2-4689-a262-06a693d7c31e)

![image_2024-02-26_22-21-15](https://github.com/U6D5T4/Auctionify/assets/89701590/0360c5df-bd11-4023-b1d4-a5844854141a)

![image_2024-02-26_22-32-00](https://github.com/U6D5T4/Auctionify/assets/89701590/484cc4f5-1d20-43f1-8f20-62091590390b)

### Affected Area

Auctionify.API.ClientApp
Auctionify.Application

### PR Checklist

_Build_

- [x] Build Succeeded

_Unit Tests_

- [x] All Tests Passed, 0 Ignored, 0 Failed

2024-02-28 06:20 UTC, otash8110 approved these changes

2024-02-28 06:26 UTC, SaidganiUsm approved these changes
Checked

2024-02-29 04:18 UTC, khasanrashidov commented
Just merged dev in dev_43 and resolved the conflicts.

2024-02-29 05:36 UTC, SaidganiUsm approved these changes

2024-03-01 07:19 UTC, TsvirkoNikita requested changes

2024-03-01 07:19 UTC, TsvirkoNikita commented on src/Auctionify.Application/Features/Reports/Query/GetAllLotsStatuses/GetAllLotsStatusesQuery.cs
> +			var query = _lotRepository.Query().Include(l => l.Seller).Where(l => l.Seller.Email == _currentUserService.UserEmail);
As it queried just for getting data, better do it without change tracking. Also, you don't need Include for Seller here, you use Seller property only in where statement, inside query context. Include is used when you need data from related entities outside the query.

2024-03-01 07:19 UTC, TsvirkoNikita commented on src/Auctionify.Application/Features/Reports/Query/GetAllLotsStatuses/GetAllLotsStatusesQuery.cs
> +						 }).ToList();
Better to use ToListAsync instead

2024-03-01 07:19 UTC, TsvirkoNikita commented on src/Auctionify.Application/Features/Reports/Query/GetCreatedLotsCount/GetCreatedLotsCountQuery.cs
Same as above

2024-03-01 07:19 UTC, TsvirkoNikita commented on src/Auctionify.Application/Features/Reports/Query/GetUserIncome/GetUserIncomeQuery.cs
Same as above

2024-03-01 09:50 UTC, khasanrashidov commented on src/Auctionify.Application/Features/Reports/Query/GetUserIncome/GetUserIncomeQuery.cs
In GetUserIncomeQuery I could still somehow refactor the code using AsNoTracking, ToListAsync and avoiding unnecessary call to BidRepository again. But I could not manage to make the following to use ToListAsync() instead of ToList(), because in that case Otabek used lots (which is list):

```
var result = (
	from data in lots // here, in other cases I could change them b/c there were IQueryable objects
	group data by data.EndDate.Date into grouped
	select new GetUserIncomeResponse
	{
		Date = grouped.Key,
		Amount = highestBids
			.Where(x => x.LotId == grouped.Last().Id)
			.Select(x => x.HighestBid)
			.FirstOrDefault(),
		Currency = grouped.Last().Currency.Code
	}
).ToList();
```

2024-03-01 09:51 UTC, khasanrashidov commented on src/Auctionify.Application/Features/Reports/Query/GetUserIncome/GetUserIncomeQuery.cs
What would you suggest doing here? Should I leave as it is, but still the code overall refactored by other things mentioned above, or would you recommend smth?

2024-03-01 09:54 UTC, khasanrashidov commented on src/Auctionify.Application/Features/Reports/Query/GetUserIncome/GetUserIncomeQuery.cs
Current refactoring on GetUserIncomeQuery

2024-03-01 10:24 UTC, TsvirkoNikita commented on src/Auctionify.Application/Features/Reports/Query/GetUserIncome/GetUserIncomeQuery.cs
@khasanrashidov in this section you are operating in memory data and it's fine. ToListAsync is relevant only for retrieving data on query from the database

2024-03-01 10:24 UTC, TsvirkoNikita approved these changes

2024-03-01 10:33 UTC, khasanrashidov commented on src/Auctionify.Application/Features/Reports/Query/GetUserIncome/GetUserIncomeQuery.cs
oh, right, I didn't notice that, we weren't retrieving data from db in that part and anyway that is operation in memory, got it)

2024-03-01 10:34 UTC, SaidganiUsm approved these changes

2024-03-01 10:35 UTC, merged