[91] - Edit the lot (Backend)
U6D5T4/Auctionify pull request #13
Opened 2023-10-17 14:05 UTC by otash8110

### Where

[NL-91 Edit the lot (Backend)](https://jjbcapital.atlassian.net/browse/NL-91)

### What

Add UpdateLot command with controller

### How

Implementation of lot updated based on UpdateLotCommand with validation and mapping profiles. Also changed language of validation errors to be in English

### Affected Area

Auctionify.API.Controllers
Auctionify.Application

### PR Checklist

_Build_

- [x] Build Succeeded

2023-10-17 17:28 UTC, TsvirkoNikita requested changes

2023-10-17 17:28 UTC, TsvirkoNikita commented on src/Auctionify.Application/Features/Lots/Commands/Update/UpdateLotCommand.cs
> +        private Lot MapLotToRequest(Lot lot, UpdateLotCommand requestLot)
Remove this method, if you don't use it

2023-10-17 17:28 UTC, TsvirkoNikita commented on src/Auctionify.Application/Features/Lots/Commands/Update/UpdateLotCommandValidator.cs
This validator is much the same as the CreateLotCommandValidator validator. Consider isolating the overall validation and reusing it

2023-10-17 17:41 UTC, otash8110 commented on src/Auctionify.Application/Features/Lots/Commands/Update/UpdateLotCommand.cs
> +        private Lot MapLotToRequest(Lot lot, UpdateLotCommand requestLot)
My bad. I forgot to remove this method during refactor

2023-10-18 16:34 UTC, otash8110 commented on src/Auctionify.Application/Features/Lots/Commands/Create/CreateLotCommand.cs
> +        public string Address { get; set; }
It was decided to make City, Country and Address fields mandatory so that DB state does not change

2023-10-19 08:10 UTC, TsvirkoNikita requested changes
Add a validation rule for StartingPrice max value. Currently, input StartingPrice > 99999 throw DB related exception

2023-10-19 08:10 UTC, TsvirkoNikita commented on src/Auctionify.Application/Features/Lots/BaseValidators/Lots/BaseLotCommandsValidator.cs
> +            RuleFor(l => l.StartingPrice)
Add a validation rule for StartingPrice max value. Currently, input StartingPrice > 99999 throw DB related exception

2023-10-19 09:37 UTC, TsvirkoNikita approved these changes

2023-10-19 09:54 UTC, merged