Dev 100
U6D5T4/Auctionify pull request #27
Opened 2023-10-27 06:54 UTC by khasanrashidov

### Where

[NL-100 Create infrastructure for saving files with Azure Blob](https://jjbcapital.atlassian.net/browse/NL-100)

### What

Set up the Azure Blob Storage infrastructure for saving photos and additional documents.

### How

Implemented Azure Blob Storage infrastructure for saving photos and additional documents. Every get, update, create, delete 
lot endpoint has blob integrated with it.

### Affected Area

Auctionify.API.Controllers
Auctionify.Application.Common
Auctionify.Application.Features
Auctionify.Infrastructure.Services
Auctionify.Infrastructure.Repositories

### PR Checklist

_Build_

- [x] Build Succeeded

2023-10-27 15:04 UTC, SevenDart requested changes

2023-10-27 15:04 UTC, SevenDart commented on src/Auctionify.API/appsettings.Development.json
> +    "ConnectionString": "DefaultEndpointsProtocol=https;AccountName=auctionify;AccountKey=swVedDpxhGOTiDo6fdHNpTqrdt5LF2lPmKeVFT3N3LjgmDqKEpic/doIWMPFr87xAb30EggwNFqN+AStmgLbjw==;EndpointSuffix=core.
You mustn't provide any credentials in public repositories, it is a security leak. You must drop this commit from the repository to remove all mentions about these credentials. When push such things as ConnectionString, use empty or default values that are not actual credentials. Credentials and app keys are secrets that should be managed separately. There a few different approaches to manage them. There are some links to these approaches in documentation about configuration: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-7.0#security-and-user-secrets

2023-10-27 15:12 UTC, khasanrashidov commented on src/Auctionify.API/appsettings.Development.json
> +    "ConnectionString": "DefaultEndpointsProtocol=https;AccountName=auctionify;AccountKey=swVedDpxhGOTiDo6fdHNpTqrdt5LF2lPmKeVFT3N3LjgmDqKEpic/doIWMPFr87xAb30EggwNFqN+AStmgLbjw==;EndpointSuffix=core.
yes, I know, that was accidentally, I didn't notice it).. no worries, I rotated the key 🗝

2023-10-27 16:55 UTC, khasanrashidov commented
Fixed, corrected, refactored as required

2023-10-27 17:00 UTC, SevenDart approved these changes

2023-10-30 10:38 UTC, SevenDart requested changes

2023-10-30 10:38 UTC, SevenDart commented on src/Auctionify.Application/Features/Lots/Commands/DeleteLotFile/DeleteLotFileCommand.cs
> +					Console.WriteLine(filePath);
Remove Console.WriteLine

2023-10-30 11:17 UTC, khasanrashidov commented on src/Auctionify.Application/Features/Lots/Commands/DeleteLotFile/DeleteLotFileCommand.cs
> +					Console.WriteLine(filePath);
fixed, removed

2023-11-02 08:49 UTC, SevenDart approved these changes

2023-11-02 08:49 UTC, SevenDart commented on src/Auctionify.Application/Common/Interfaces/IEmailService.cs
> +		public Task SendEmailAsync(string toEmail, string subject, string content);
There is no any sense in adding keyword "public" when defining interface methods, all members are public by default. It has sense only if you want to use another modifier for some methods, to distinct public from private/protected.

2023-11-02 08:49 UTC, SevenDart commented on src/Auctionify.Application/Common/Interfaces/IWatchlistService.cs
> +		public Task<bool> IsLotInUserWatchlist(int lotId, int userId, CancellationToken cancellationToken);
Same with previous interface

2023-11-02 09:31 UTC, khasanrashidov commented on src/Auctionify.Application/Common/Interfaces/IEmailService.cs
> +		public Task SendEmailAsync(string toEmail, string subject, string content);
fixed

2023-11-02 09:32 UTC, khasanrashidov commented on src/Auctionify.Application/Common/Interfaces/IWatchlistService.cs
> +		public Task<bool> IsLotInUserWatchlist(int lotId, int userId, CancellationToken cancellationToken);
fixed

2023-11-02 09:40 UTC, SevenDart submitted a review, later dismissed

2023-11-02 09:59 UTC, SaidganiUsm approved these changes

2023-11-02 09:59 UTC, merged