[104] Unit tests for Auth logic
U6D5T4/Auctionify pull request #36
Opened 2023-11-06 06:41 UTC by khasanrashidov

### Where

[NL-104 Unit tests for Auth logic](https://jjbcapital.atlassian.net/browse/NL-104)

### What

Wrote Unit Tests for Authentication (i.e. Identity Service: Login, Register, Token Generating and so on.)

### How

Wrote Unit tests for all Identity Service Methods. Test Coverage for both services which are being tested and the tests that are testing those services is 100%. Testing code was refactored. (DRY)

### Affected Area

Auctionify.UnitTests.IdentityServiceUnitTests

### PR Checklist

_Build_

- [x] Build Succeeded

_Unit Tests_

- [x] All Tests Passed

2023-11-07 09:16 UTC, TsvirkoNikita requested changes
Project with tests has build errors in FilterLotsTests class:
![image](https://github.com/U6D5T4/Auctionify/assets/35694505/afc420f8-9d60-4759-a590-d4741ef8d0a9)

2023-11-07 20:39 UTC, khasanrashidov commented
fixed

2023-11-09 15:49 UTC, TsvirkoNikita requested changes

2023-11-09 15:49 UTC, TsvirkoNikita commented on tests/Auctionify.UnitTests/IdentityServiceUnitTests/IdentityServiceUnitTests.cs
> +			var sut = new IdentityService(
What is mean this name for variable?

2023-11-09 15:49 UTC, TsvirkoNikita commented on tests/Auctionify.UnitTests/IdentityServiceUnitTests/IdentityServiceUnitTests.cs
Could you also add tests for the LoginUserWithGoogle method?

2023-11-09 17:20 UTC, khasanrashidov commented on src/Auctionify.API/appsettings.Development.json
> -  "AppUrl": "https://localhost:7230",
Yes, you are right)) I already changed them in Azure like a week ago)))) in both dev and prod slots))

2023-11-09 17:27 UTC, khasanrashidov commented on src/Auctionify.API/Controllers/LotsController.cs
> +		[HttpGet("filtered-lots")]
actually it is adjective (прилагательное: отфильтрованные лоты)... I thought it is possible, because this endpoint returns filtered lots... (I did it on purpose so it doesn't sound as verb (because as you know in Restful APIs we don't use verbs), so I thought "filter-lots" sounds incorrectly), if it is not, I will change to "filter-lots", what do you think?

2023-11-09 17:28 UTC, khasanrashidov commented on src/Auctionify.Infrastructure/Persistence/ApplicationDbContextInitializer.cs
> +				await _context.SaveChangesAsync();
yes, right... I just added (for some test, to check something quickly)... and forgot to remove, my bad))

2023-11-09 17:44 UTC, khasanrashidov commented on tests/Auctionify.UnitTests/IdentityServiceUnitTests/IdentityServiceUnitTests.cs
> +			var sut = new IdentityService(
System Under Test (SUT), 
In the context of the IdentityServiceUnitTests class, sut is an instance of the IdentityService class, and it is the System Under Test (SUT) that we want to test.

2023-11-09 17:45 UTC, khasanrashidov commented on tests/Auctionify.UnitTests/IdentityServiceUnitTests/IdentityServiceUnitTests.cs
Oh, right.... that one appeared after I merged with dev... I didn't notice it... will do it!)) Thank you for noticing!

2023-11-09 17:50 UTC, khasanrashidov commented on src/Auctionify.Infrastructure/Persistence/ApplicationDbContextInitializer.cs
> +				await _context.SaveChangesAsync();
fixed, removed that

2023-11-10 06:24 UTC, khasanrashidov commented on tests/Auctionify.UnitTests/IdentityServiceUnitTests/IdentityServiceUnitTests.cs
unit tests for login with google are ready.

2023-11-10 08:30 UTC, TsvirkoNikita commented on src/Auctionify.API/Controllers/LotsController.cs
> +		[HttpGet("filtered-lots")]
Ok, got it, it's fine

2023-11-10 08:33 UTC, TsvirkoNikita commented on src/Auctionify.Infrastructure/Persistence/ApplicationDbContextInitializer.cs
> +				await _context.SaveChangesAsync();
Still see a few SaveChangesAsync calls in TrySeedAsync(). I meant that you could remove all those calls in if statements and call SaveChangesAsync only once in the end of the TrySeedAsync method

2023-11-10 09:20 UTC, khasanrashidov commented on src/Auctionify.Infrastructure/Persistence/ApplicationDbContextInitializer.cs
> +				await _context.SaveChangesAsync();
You know we have some categories (parent categories) and their sub categories (e.g. electronics -> phones).. When I save changes in the end it throws exception... because when I create sub category it references the parent category (which doesn't exist until I save parent category).
The case where I need it:
![image](https://github.com/U6D5T4/Auctionify/assets/89701590/5b35cefd-b603-45c3-8c8a-d583bc29b85a)

The same thing with sample locations, I cannot reference it until it is saved in the context of db
![image](https://github.com/U6D5T4/Auctionify/assets/89701590/f94e597c-5aee-48f5-ac57-88b1f07d8d5f)


However, I removed it from currency part:

![image](https://github.com/U6D5T4/Auctionify/assets/89701590/11976001-47f1-4493-a73c-fa7d5f2a0561)

2023-11-10 09:22 UTC, khasanrashidov commented on src/Auctionify.Infrastructure/Persistence/ApplicationDbContextInitializer.cs
> +				await _context.SaveChangesAsync();
that's it I pushed the corrections

2023-11-10 11:40 UTC, TsvirkoNikita approved these changes

2023-11-10 13:49 UTC, merged