[82,84] - Create lot/auction (Save as draft)(Frontend)
U6D5T4/Auctionify pull request #37
Opened 2023-11-07 16:19 UTC by otash8110

### Where

[NL-82 Create lot/auction](https://jjbcapital.atlassian.net/browse/NL-82)

### What

Implement create-lot page for sellers and additional changes.

### How

add seller-navigation which is shown only to sellers. refactor authorize services and interceptors, configure routing. Add endpoint for receiving currencies metadata. Make pages addaptive

### Affected Area

Auctionify.API.ClientApp
Auctionify.Application.Features.Currencies

### PR Checklist

_Build_

- [x] Build Succeeded

_Unit Tests_

- [x] X Tests Passed, Y Ignored, Z Failed

2023-11-10 14:01 UTC, TsvirkoNikita requested changes
- Fix the responsiveness of the layout:
![image](https://github.com/U6D5T4/Auctionify/assets/35694505/99892fd0-a2ae-4569-9ce2-699e101d2f1c)
- Make it possible to add up to 20 photos
- According to the requirements, the maximum number of documents that can be uploaded is 3
- Validation errors should be displayed correctly:
![image](https://github.com/U6D5T4/Auctionify/assets/35694505/720e93af-8adb-4764-bc8a-c86b8bce02c8)
- When you press Submit or Save as draft, both buttons are pressed at the same time
- Popups are not hidden when you click outside (consider replacing them with material ui built-in Dialog component)
- Fix this button
![image](https://github.com/U6D5T4/Auctionify/assets/35694505/fe36f1b1-8c80-43f6-9fa5-cbdb55e73556)

2023-11-14 06:50 UTC, khasanrashidov commented
You have two User controllers: UsersController.cs and UserController.cs. Merge their contents and leave one as UsersController.cs.

2023-11-14 15:53 UTC, TsvirkoNikita requested changes
- Remove all console.log() calls
- Buttons remains red after filling popups
![image](https://github.com/U6D5T4/Auctionify/assets/35694505/d2746137-d246-4c66-ba77-af89de7bf1db)
![image](https://github.com/U6D5T4/Auctionify/assets/35694505/b9cfa00d-9537-43fb-bd30-04788f44ffd7)
- Fix the error message so that it is fully visible
![image](https://github.com/U6D5T4/Auctionify/assets/35694505/6dd3c1e8-c152-48a9-b0b8-8b559503f274)
- Could you please update these buttons so that after setting values in popups, they show those values as it is on figma?
![image](https://github.com/U6D5T4/Auctionify/assets/35694505/98968279-b92b-49eb-a27d-88f258683be5)

2023-11-14 16:12 UTC, TsvirkoNikita requested changes

2023-11-14 16:12 UTC, TsvirkoNikita commented on src/Auctionify.API/ClientApp/src/app/components/seller/create-lot/create-lot.component.scss
Remove empty rulesets

2023-11-14 16:12 UTC, TsvirkoNikita commented on src/Auctionify.API/ClientApp/src/app/components/seller/create-lot/create-lot.component.html
> +                            <div class="buttons location-btn">
What the reason to use classes without style (location-btn, starting-price-btn, file-btn)?

2023-11-14 19:47 UTC, TsvirkoNikita approved these changes

2023-11-15 07:10 UTC, SaidganiUsm approved these changes
Checked

2023-11-15 07:21 UTC, merged