[75] Reset password (Frontend)
U6D5T4/Auctionify pull request #42
Opened 2023-11-14 10:23 UTC by SaidganiUsm

Where
[Reset password (Frontend)](https://jjbcapital.atlassian.net/browse/NL-75)

What
Forget and reset password pages

How
Designed the page for changing password for the user 

Affected Area
Auctionify.API
Auctionify.Infrastructure

PR Checklist
Build

 Build Succeeded
Unit Tests

 X Tests Passed, Y Ignored, Z Failed

2023-11-15 10:37 UTC, khasanrashidov commented on src/Auctionify.API/ClientApp/src/app/api-authorization/authorize.service.ts
> +      //this.initializeAuthorizeService();
do we need this comment?)

2023-11-23 00:35 UTC, khasanrashidov commented
Can you merge and resolve conflicts as well? It should be guaranteed that after merge your application works))

2023-11-28 06:41 UTC, khasanrashidov commented
Fix it:

![image](https://github.com/U6D5T4/Auctionify/assets/89701590/ae3d05d0-cc4e-4e7b-a2b2-9035c86df639)

![image](https://github.com/U6D5T4/Auctionify/assets/89701590/382e1b81-6dfc-4952-84a9-f311e18f4a31)

2023-11-30 09:50 UTC, TsvirkoNikita requested changes
Link didn't work
![image](https://github.com/U6D5T4/Auctionify/assets/35694505/5ee1553b-c2a5-41b2-8883-d5853ae32749)

2023-11-30 11:14 UTC, khasanrashidov approved these changes

2023-11-30 11:14 UTC, merged