[107] - Filter lots (Frontend)
U6D5T4/Auctionify pull request #44
Opened 2023-11-15 19:16 UTC by otash8110

### Where

[NL-107 Filter lots (Frontend)](https://jjbcapital.atlassian.net/browse/NL-107)

### What

Add filter component

### How

Implement filter component as Pop-up. Add GetAllLocations to API for filter metadata, add client requests for filter and getAllLocations endpoint for frontend. Enhance getAllLotStatuses to include additional statuses as a response. Add unit tests for getAllLocations

### Affected Area

Auctionify.API.Controllers
Auctionify.API.ClientApp
Auctionify.Application.Features
Auctionify.Infrastructure

### PR Checklist

_Build_

- [x] Build Succeeded

_Unit Tests_

- [x] 48 Tests Passed, 0 Ignored, 0 Failed

2023-11-16 07:12 UTC, khasanrashidov submitted a review, later dismissed
Backend with unit tests are well written, frontend for buyer and filter looks good to me

2023-11-20 09:24 UTC, TsvirkoNikita requested changes

2023-11-20 09:24 UTC, TsvirkoNikita commented on src/Auctionify.API/ClientApp/src/app/components/buyer/filter/filter.component.ts
> +        this.populateCategorySelector();
It's better to do initialization calls inside ngOnInit

2023-11-23 04:10 UTC, khasanrashidov submitted a review, later dismissed

2023-11-23 10:37 UTC, TsvirkoNikita requested changes
It has become impossible to filter out lots with a low value with the slider. I suggest limiting the price range to the maximum price of the existing lots.

![image](https://github.com/U6D5T4/Auctionify/assets/35694505/2460890a-66e3-4806-bf22-2f3e9e18e6c1)

2023-11-28 07:30 UTC, khasanrashidov approved these changes

2023-11-28 09:47 UTC, TsvirkoNikita approved these changes

2023-11-28 11:08 UTC, merged