[72] - Login (Backend)
U6D5T4/Auctionify pull request #5
Opened 2023-10-05 10:19 UTC by otash8110

### Where

[NL-72 Login (Backend)](https://jjbcapital.atlassian.net/browse/NL-72)

### What

Implementation of login process

### How

Added Login endpoint, IdentityService method for Login, private method for JWT Token generation, and input/output model classes

### Affected Area

Auctionify.API.Controllers
Auctionify.API.Program.cs
Auctionify.API.appsettings.json
Auctionify.Application.Common.Models.Account
Auctionify.Application.Common.Interfaces
Auctionify.Infrastructure.ConfigureServices.cs
Auctionify.Infrastructure.Identity.IdentityService

### PR Checklist

_Build_

- [x] Build Succeeded

_Unit Tests_

- [x] Not included

2023-10-05 10:20 UTC, otash8110 commented
[3afbed6](https://github.com/U6D5T4/Auctionify/pull/5/commits/3afbed6729475f772b256b368e468fb87caa5c69) commit has wrong ticket number because of typo

2023-10-05 11:02 UTC, TsvirkoNikita requested changes

2023-10-05 11:02 UTC, TsvirkoNikita commented on src/Auctionify.Application/Common/Models/Account/UserManagerResponse.cs
> +        public object Result { get; set; }
According to my previous comment, remove this property if it's common model and specify a specific type if it's for Login only.

2023-10-05 11:02 UTC, TsvirkoNikita commented on src/Auctionify.Infrastructure/Identity/IdentityService.cs
> +            var result = await signInManager.PasswordSignInAsync(user, userModel.Password, false, false);
If user null here, you get an exception. You need to handle this case.

2023-10-06 06:34 UTC, TsvirkoNikita approved these changes

2023-10-06 06:46 UTC, merged