[126] - Sprint4 fixing
U6D5T4/Auctionify pull request #56
Opened 2023-11-19 09:42 UTC by otash8110

### Where

[NL-126 Sprint4 fixing](https://jjbcapital.atlassian.net/browse/NL-126)

### What

Fix functionality implemented in sprint 4

### How

Change browser tab icon and title, remove starting price limit, messsage when adding existing images and when adding existing files

### Affected Area

Auctionify.API.ClientApp
Auctionify.Infrastructure
Auctionify.Application.Features

### PR Checklist

_Build_

- [x] Build Succeeded

_Unit Tests_

- [x] 46 Tests Passed, 0 Ignored, 0 Failed

2023-11-19 14:51 UTC, khasanrashidov approved these changes
Looks Good To Me! Every issue that was addressed during the review was fixed. Approved!

2023-11-20 06:42 UTC, TsvirkoNikita requested changes

2023-11-20 06:42 UTC, TsvirkoNikita commented on src/Auctionify.API/ClientApp/src/app/components/seller/create-lot/create-lot.component.ts
> -                Validators.max(9999),
It's not necessary to completely remove the upper limit for the price, it's enough to raise it to a large value, I think up to a trillion would be enough

2023-11-20 16:58 UTC, khasanrashidov commented on src/Auctionify.API/ClientApp/src/app/components/seller/create-lot/create-lot.component.ts
> -                Validators.max(9999),
Fixed, maximums is trillion, the validation message is fixed as well ("maximum starting price is 1000000000000")

2023-11-20 20:08 UTC, TsvirkoNikita requested changes

2023-11-20 20:08 UTC, TsvirkoNikita commented on src/Auctionify.API/ClientApp/src/app/components/seller/create-lot/pop-ups/currency/currency.component.ts
> -                Validators.max(9999),
Update validation here too

2023-11-21 02:46 UTC, khasanrashidov commented on src/Auctionify.API/ClientApp/src/app/components/seller/create-lot/pop-ups/currency/currency.component.ts
> -                Validators.max(9999),
corrected validation for max in currency component as well

2023-11-21 07:17 UTC, TsvirkoNikita approved these changes

2023-11-21 12:18 UTC, khasanrashidov approved these changes

2023-11-21 12:42 UTC, merged