[94] Browse auctions (Frontend)
U6D5T4/Auctionify pull request #57
Opened 2023-11-21 06:31 UTC by SaidganiUsm

Where
[Browse auctions (Frontend)](https://jjbcapital.atlassian.net/browse/NL-94)

What
See all lost in the auction

How
Browsing the auction

Affected Area
Auctionify.API

PR Checklist
Build

 Build Succeeded
Unit Tests

 X Tests Passed, Y Ignored, Z Failed

2023-11-25 07:41 UTC, khasanrashidov commented
some things are to be fixed:

1) icons are not showing properly

![image](https://github.com/U6D5T4/Auctionify/assets/89701590/ce0642b0-1eb7-4a37-963e-c8ce4b6d3d8c)

2) browse auctions (get all lots), horizontally need to be displayed, and wishlist icon should be displayed properly as well:

![image](https://github.com/U6D5T4/Auctionify/assets/89701590/e5c0c4e5-27e0-4868-bf5d-6d6f7e194e72)

2023-11-26 17:07 UTC, khasanrashidov commented
these things are to be fixed:

![image](https://github.com/U6D5T4/Auctionify/assets/89701590/d2aefac5-51db-4a8b-8084-d745f01e3f47)


![image](https://github.com/U6D5T4/Auctionify/assets/89701590/67bad09d-82b0-44c5-b476-8e6e02bb50f6)

2023-11-28 04:40 UTC, khasanrashidov commented
Please, Saidgani, icons are to be corrected

![image](https://github.com/U6D5T4/Auctionify/assets/89701590/9e408710-334d-45fb-8473-fdcd96209a42)


![image](https://github.com/U6D5T4/Auctionify/assets/89701590/02d204e6-e054-4ce1-97fb-5c3097709bb2)


![image](https://github.com/U6D5T4/Auctionify/assets/89701590/3dfec0fa-0ece-4a57-9785-7d8bab05f0e5)

2023-11-29 00:05 UTC, khasanrashidov commented on src/Auctionify.API/ClientApp/src/app/components/buyer/buyer-routing.module.ts
> +const sellerRoutes: Routes = [
I think it is buyerRoutes

2023-12-04 14:08 UTC, otash8110 approved these changes
Minor differences with design. Overall implementation seems fine for me

2023-12-04 16:01 UTC, TsvirkoNikita requested changes
![image](https://github.com/U6D5T4/Auctionify/assets/35694505/f4a0bd98-90f1-4fba-82a4-5dd832535f03)
- remove 'Example' links
- sorting does not work
- pagination button for active lots does not work
- all auctions are always pulled from the backend, despite the filter endpoint support pagination.
- if a row of lots does not fit on the screen, the lots should be moved to the next row. There should be no horizontal scrolling on the page

2023-12-06 07:49 UTC, otash8110 requested changes
![image](https://github.com/U6D5T4/Auctionify/assets/72335218/0144c778-8884-472b-ae76-4598f465f0b2)
- Remove example links on top
- Lots still do not wrap, it creates horizontal scroll on screen sizes 1400px. I Suggest using flexbox
- Sort button still not sorting but just has a pointer cursor. I suggest removing it if there is no this functionality

![image](https://github.com/U6D5T4/Auctionify/assets/72335218/8852d0c4-f705-4e5c-857c-040dea0ed8ad)
- I think it is a good idea to make those buttons invisible when there are no lots in any of the given statuses. 

![image](https://github.com/U6D5T4/Auctionify/assets/72335218/7bacc9ed-8e7d-44ac-8003-3ee7c9895cf4)
- Fix text style for lots and make other lot statuses' lots also clickable as Active lots

2023-12-08 15:44 UTC, khasanrashidov commented
1. When I configured the price only in filter (set the range max)... the upcoming lot also was shown to me.. but I didn't check the upcoming lot checkbox in filter:
filter:
![image](https://github.com/U6D5T4/Auctionify/assets/89701590/cdd13b3e-2c5b-416f-aa44-5abd8e68f11a)

what I got (that one within red is upcoming lot):
![image](https://github.com/U6D5T4/Auctionify/assets/89701590/1ccc2a01-0452-483d-9378-2c2eba07af20)

2. Bid count didn't load, although in DB for lots, I have them

![image](https://github.com/U6D5T4/Auctionify/assets/89701590/271681da-a73c-42f7-8912-bcdd950c9fb5)


3. Can you add hovering effect with shadow +  cursor: pointer, because here we don't have borders in design, so for user it would be convenient to browse lots:

![image](https://github.com/U6D5T4/Auctionify/assets/89701590/687cbb73-bec7-4017-b0f8-57a861ae7b12)

4. Can you add watchlist (wishlist) functionality? So buyer (who logged in), can add them. The watchlist functionality is currently available in dev_111

![image_2023-12-08_20-44-27](https://github.com/U6D5T4/Auctionify/assets/89701590/8b336fb0-b0a1-4167-9833-166962ac75eb)

2023-12-09 05:01 UTC, khasanrashidov commented
### 1. Resolve conflicts.

### 2. Remove that, we are returning currency code from API (what if you have roubles, or soums in currency?)
![image](https://github.com/U6D5T4/Auctionify/assets/89701590/af6d78d8-a16e-42c6-b091-5fe304b4a701)

### 3. I would a bit space between them:
![image](https://github.com/U6D5T4/Auctionify/assets/89701590/32f930e6-8059-4c6a-85b0-dad728face9b)

2023-12-11 08:20 UTC, otash8110 approved these changes

2023-12-11 09:39 UTC, TsvirkoNikita requested changes
- For each auction, if it has bids, you need to show its actual price, not the starting price
- Why did you remove the sort button?
- The filter is applied only to the upper section with active lots and in this case lots in different statuses start to be displayed there. The filter should be applied to each section. If we select, for example, only active lots in the filter, then only the upper section with active lots will be displayed
- Lots row still not responsive:
![image](https://github.com/U6D5T4/Auctionify/assets/35694505/db1f9e6f-c9d5-4812-a18a-09edbc3d3aa5)

2023-12-11 12:17 UTC, otash8110 commented
> * For each auction, if it has bids, you need to show its actual price, not the starting price
> * Why did you remove the sort button?
> * The filter is applied only to the upper section with active lots and in this case lots in different statuses start to be displayed there. The filter should be applied to each section. If we select, for example, only active lots in the filter, then only the upper section with active lots will be displayed
> * Lots row still not responsive:
>   ![image](https://private-user-images.githubusercontent.com/35694505/289482679-db1f9e6f-c9d5-4812-a18a-09edbc3d3aa5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODc4OTIsIm5iZiI6MTcwMjI4NzU5MiwicGF0aCI6Ii8zNTY5NDUwNS8yODk0ODI2NzktZGIxZjllNmYtYzlkNS00ODEyLWExOGEtMDllZGJjM2QzYWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA5Mzk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViOWZhNmY3MGZiMGY4ZjIyMDc0MmIxYzNkZWY5ZjJiNWYxZjgyYTUyZDYzNzA5NmQ1MDBkMjJkYmI3OTk2YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zjmn5LAWmIRXX5LMUxhefawKb7ue2moG42z9iPvlzu4)

Fixed filter

2023-12-12 14:44 UTC, TsvirkoNikita requested changes
- Price filtering still using the starting price of the lot, instead the current price
- Selecting a specific status in the filter has no effect
![image](https://github.com/U6D5T4/Auctionify/assets/35694505/347a6713-791c-457b-8777-bb608c064143)

2023-12-12 22:11 UTC, TsvirkoNikita approved these changes

2023-12-12 22:14 UTC, otash8110 approved these changes

2023-12-12 22:14 UTC, merged