[76] Sign-up (Backend)
U6D5T4/Auctionify pull request #6
Opened 2023-10-05 10:59 UTC by SaidganiUsm

### Where

[NL-76 Sign up (Backend)](https://jjbcapital.atlassian.net/browse/NL-76)

### What

Implemented sign-up process

### How

Added Sign-up endpoint, IdentityService method for Sign-up, private method for JWT Token generation, and input/output model classes

### Affected Area

Auctionify.API.Controllers
Auctionify.API.Program.cs
Auctionify.API.appsettings.json
Auctionify.Application.Common.Models.Account
Auctionify.Application.Common.Interfaces
Auctionify.Infrastructure.ConfigureServices.cs
Auctionify.Infrastructure.Identity.IdentityService

### PR Checklist

_Build_

- [x] Build Succeeded

_Unit Tests_

- [x] X Tests Passed, Y Ignored, Z Failed

2023-10-05 11:04 UTC, TsvirkoNikita approved these changes
Change target branch first of all :)

2023-10-05 11:05 UTC, TsvirkoNikita requested changes
Change target branch first of all :)

2023-10-05 11:43 UTC, SaidganiUsm commented
Sorry, I have changed the target branch

2023-10-06 10:26 UTC, TsvirkoNikita requested changes

2023-10-06 10:26 UTC, TsvirkoNikita commented on src/Auctionify.API/Controllers/AuthController.cs
> +            return BadRequest("Some properties are not valid"); // statusCode: 400 (something wrong with client request)
Please, remove obvious comments from code like that

2023-10-06 10:26 UTC, TsvirkoNikita commented on src/Auctionify.API/Controllers/AuthController.cs
> +                return Redirect($"{configuration["AppUrl"]}/confirmemail.html");
Instead of redirecting to a html page, it is better to create a View and return it as a response

2023-10-06 10:26 UTC, TsvirkoNikita commented on src/Auctionify.Application/Common/Interfaces/IIdentityService.cs
> +        Task<UserManagerResponse> ConfirmUserEmailAsync(string userId, string token); // why namely userId and token? because we need to confirm the email of a specific user
Remove this comment, it's useless. The name of the method should briefly and clearly describe it, not a comment in the interface

2023-10-06 10:26 UTC, TsvirkoNikita commented on src/Auctionify.Application/Common/Models/Account/UserManagerResponse.cs
> +    public class UserManagerResponse // This is the model that the server will send back to the user
Please use approach with base model which you have in dev branch already

2023-10-09 17:37 UTC, SaidganiUsm commented
apiKey is inside the user secrets, and I will send it to you on Skype.

2023-10-09 20:52 UTC, TsvirkoNikita approved these changes

2023-10-11 09:30 UTC, TsvirkoNikita approved these changes

2023-10-11 10:59 UTC, merged