[111, 88] Lot profile (Seller/Buyer) (Frontend)
U6D5T4/Auctionify pull request #62
Opened 2023-11-27 05:21 UTC by SaidganiUsm

Where
[Browse auctions (Frontend)](https://jjbcapital.atlassian.net/browse/NL-94)
[View seller lot profile (Frontend)](https://jjbcapital.atlassian.net/browse/NL-88)

What
View for lot profile (seller and buyer)

How
View lot profile for buyer and seller with routing and all functions

Affected Area
Auctionify.API

PR Checklist
Build

 Build Succeeded
Unit Tests

 X Tests Passed, Y Ignored, Z Failed

2023-11-28 19:59 UTC, khasanrashidov reviewed
and please merge with dev as well, resolve conflicts

2023-11-28 19:59 UTC, khasanrashidov commented on src/Auctionify.API/ClientApp/src/app/web-api-client.ts
> +        let url_ = this.baseUrl + `/api/lots/${id}/buyer`;
Please fix it, it is, '/buyers' (in plural):

let url_ = this.baseUrl + `/api/lots/${id}/buyers`;

2023-12-04 16:35 UTC, khasanrashidov commented
1. Your branch is outdated and doesn't have SignalR (which is in dev), I suggest upgrading the your branch and integrating it.

2.  why don't we keep consistency and call the route (path) to get lot as 'get-lot/:id'

![image](https://github.com/U6D5T4/Auctionify/assets/89701590/61827f6c-1ee5-4186-8213-226c9446cde6)

3. I could not get the lot profile for seller: (used https://localhost:44452/seller/lot-profile/2)

![image](https://github.com/U6D5T4/Auctionify/assets/89701590/14cfc5d6-060b-4507-9f6c-792048f8ecb7)

2023-12-04 18:44 UTC, otash8110 requested changes
![image](https://github.com/U6D5T4/Auctionify/assets/72335218/ef6c7221-3fcc-4cc1-87e3-350bf68c6fd1)

- Add styles for the block of images on the left from main image. 
- Add blue block from design which contains price information on right side
- Merge dev with bids functionality and implement bids block on right side
- I cannot get a lot profile as a seller

![image](https://github.com/U6D5T4/Auctionify/assets/72335218/4cb4fdb8-5013-4351-b22c-8597e851b690)
-Fix images block for cases when there are no any images

![image](https://github.com/U6D5T4/Auctionify/assets/72335218/b892fd0b-5c11-4d8a-86a4-3842624b114f)
- If there is a parect category it shows id, not parent category name

![image](https://github.com/U6D5T4/Auctionify/assets/72335218/81bcaa37-2eb7-4372-89e2-96c1c4dd8683)
- fix documents and files styles

2023-12-04 18:44 UTC, otash8110 commented on src/Auctionify.API/ClientApp/src/app/components/buyer/buyer-routing.module.ts
> +    }
I suggest making lot-profile general path, not only for buyer or seller. So, please move it to general routing module

2023-12-07 06:35 UTC, khasanrashidov commented
Here can you show the actual number of bids for the lot, as it is in figma (we have it in the response of API as bidCount):

![image_2023-12-07_11-30-25](https://github.com/U6D5T4/Auctionify/assets/89701590/93f38069-0be6-4ae2-b998-c9388ad7182a)

what we have in figma:

![image](https://github.com/U6D5T4/Auctionify/assets/89701590/1625c703-9a50-47ac-b548-af8e132932b1)

I don't know if I am going too much on that (I mean styling), but these styles differ, and does it matter (for below)?
### what we have:
![image](https://github.com/U6D5T4/Auctionify/assets/89701590/a233669e-e1da-498a-b4dc-b5ba23ee17b1)
### what is in figma design:
![image](https://github.com/U6D5T4/Auctionify/assets/89701590/5f62484e-397a-455b-ba4f-424957a7fe42)

2023-12-07 06:41 UTC, khasanrashidov commented
is it possible to make the image clickable, so that when I click the image it shows the larger one, right now it is not possible (or if it is not, then you may consider not to include it:

![image](https://github.com/U6D5T4/Auctionify/assets/89701590/d9fa6aa8-6f80-4d8e-8d35-e27e1eaaaef6)

2023-12-08 10:42 UTC, khasanrashidov approved these changes

2023-12-08 16:09 UTC, khasanrashidov approved these changes
Checked, works good! Requested changes were applied, looks good to me.

update:
fix issue below

2023-12-10 12:07 UTC, khasanrashidov approved these changes

2023-12-10 12:07 UTC, khasanrashidov commented on src/Auctionify.API/ClientApp/src/app/components/general/lot-profile/lot-profile.component.html
> +                            <p>{{ bid.newPrice | currency: 'USD' }}</p>
Fixed thank you!

2023-12-13 10:41 UTC, otash8110 requested changes
![image](https://github.com/U6D5T4/Auctionify/assets/72335218/d11d84b1-17f6-4e49-92c6-87aa335fa311)
When I try to change user data I get validation error without message

![image](https://github.com/U6D5T4/Auctionify/assets/72335218/e2242cda-b8b1-47dd-9b02-eaaf3642d6f8)
- Log out is not working because of the wrong type of the dialog (Should be just Dialog) and overload method of the open. See other components which have such functionality.

![image](https://github.com/U6D5T4/Auctionify/assets/72335218/c86e41a7-1b30-4434-bc06-c015cd8d1377)
- When I click on eye to show hidden password the form is submited. Also add some space between inputs because message cannot fit

2023-12-13 10:47 UTC, otash8110 submitted a review, later dismissed

2023-12-13 10:53 UTC, Muhammad-gf approved these changes

2023-12-13 11:08 UTC, otash8110 approved these changes

2023-12-13 11:09 UTC, khasanrashidov approved these changes

2023-12-13 11:09 UTC, merged