Dev 56
U6D5T4/Auctionify pull request #7
Opened 2023-10-05 17:03 UTC by khasanrashidov

### Where

[NL-56 Implement DB solution based on investigation results](https://jjbcapital.atlassian.net/browse/NL-56)

### What

Provide a description of the goal of these changes

### How

Implemented business models according to the Db structure (schema).

### Affected Area

Auctionify.Core
Auctionify.Infrastructure

### PR Checklist

_Build_

- [x] Build Succeeded

2023-10-06 08:25 UTC, khasanrashidov commented
![image_2023-10-05_21-44-46](https://github.com/U6D5T4/Auctionify/assets/89701590/c94de2ef-cc4f-49fb-a2a9-dee991780012)

2023-10-06 14:27 UTC, TsvirkoNikita requested changes

2023-10-06 14:27 UTC, TsvirkoNikita commented on src/Auctionify.Core/Entities/Rate.cs
> +		public uint RatingValue { get; set; }
What is the matter to use uint type here? It maps to bigint in sql, which more than just int. Looks like byte it's more suitable here

2023-10-06 14:27 UTC, TsvirkoNikita commented on src/Auctionify.Infrastructure/Data/Config/RateConfiguration.cs
> +			builder.Property(r => r.RatingValue).HasMaxLength(5).IsRequired(true);
HasMaxLength is using to specify a maximum length, not value. You need to change the type for RatingValue

2023-10-08 20:14 UTC, TsvirkoNikita requested changes

2023-10-08 20:14 UTC, TsvirkoNikita commented on src/Auctionify.Core/Entities/Rate.cs
> +		public int LoId { get; set; }
Fix the typo

2023-10-09 07:39 UTC, TsvirkoNikita approved these changes

2023-10-09 18:57 UTC, merged