[120, 122] Place a bid (Frontend) and Re-bid on the lot (Frontend) respectively
U6D5T4/Auctionify pull request #77
Opened 2023-12-06 20:09 UTC by khasanrashidov

### Where

[NL-120 Place a bid (Frontend)](https://jjbcapital.atlassian.net/browse/NL-120)
[NL-122 Re-bid on the lot (Frontend)](https://jjbcapital.atlassian.net/browse/NL-122)

### What

Developing the ability to bid and rebid on frontend for buyers.

### How

Implemented the features on frontend fully on buyer lot profile. I need to mention that fact that buyer lot profile was not ready yet, so I had to write simple html lot profile for buyer (which can be rewritten by another team member) and included there a simple button which opens real styled component to bid/rebid for buyers (as it is shown in Figma). Every case was taken into consideration, so that component functions fully without any problems.

To access/test the component, simply go to the url: https://localhost:44452/buyer/get-lot/2

### Affected Area

Auctionify.API.ClientApp

### PR Checklist

_Build_

- [x] Build Succeeded

_Unit Tests_

- [x] ALL (63) Tests Passed, 0 Ignored, 0 Failed

2023-12-06 20:16 UTC, khasanrashidov commented
some photos:

![image_2023-12-07_00-28-22](https://github.com/U6D5T4/Auctionify/assets/89701590/32b6e0c9-6b5b-49d7-bf44-4abfd29318d5)

![image](https://github.com/U6D5T4/Auctionify/assets/89701590/0899ad94-b1de-4b7b-b53d-7bc0267f9090)

![image](https://github.com/U6D5T4/Auctionify/assets/89701590/4d8311cb-1083-4c7f-a008-1c99d23c86b7)


![image](https://github.com/U6D5T4/Auctionify/assets/89701590/d989dd5e-b574-496f-9d0f-3b533de6ba42)

2023-12-07 10:08 UTC, otash8110 submitted a review, later dismissed

2023-12-07 10:52 UTC, TsvirkoNikita requested changes

2023-12-07 10:52 UTC, TsvirkoNikita commented on src/Auctionify.API/ClientApp/src/app/components/buyer/add-bid/add-bid.component.ts
> +            control.value < this.startingPrice
Change this condition to <=, because now if you put a value equal to startingPrice, the request will be submitted

2023-12-07 11:57 UTC, khasanrashidov commented on src/Auctionify.API/ClientApp/src/app/components/buyer/add-bid/add-bid.component.ts
> +            control.value < this.startingPrice
fixed

2023-12-07 12:07 UTC, merged