[124] Withdraw a bid (Frontend)
U6D5T4/Auctionify pull request #79
Opened 2023-12-09 15:37 UTC by khasanrashidov

### Where

[NL-124 Withdraw a bid (Frontend)](https://jjbcapital.atlassian.net/browse/NL-124)

### What

Developing the frontend modal component to enable buyers to withdraw their bids (according to rules in backend).

### How

Implemented the features on frontend fully on buyer lot profile. Now buyers can withdraw their bids. All validation cases are considered and proper messages provided for any success and error cases.

### Affected Area

Auctionify.API.ClientApp
Auctionify.Application.Features.Users

### PR Checklist

_Build_

- [x] Build Succeeded

_Unit Tests_

- [x] All Tests Passed, 0 Ignored, 0 Failed

2023-12-09 16:19 UTC, SaidganiUsm requested changes
![Снимок экрана 2023-12-09 211502](https://github.com/U6D5T4/Auctionify/assets/121709409/0b4adb32-bbb5-494d-a3e5-913335883789)

Everything is perfectly done. But I will recommend adding a tiny bit of fix as a closing btn in the window of placing the bid.

2023-12-09 16:26 UTC, khasanrashidov commented
> ![Снимок экрана 2023-12-09 211502](https://private-user-images.githubusercontent.com/121709409/289286394-0b4adb32-bbb5-494d-a3e5-913335883789.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzkxMzQsIm5iZiI6MTcwMjEzODgzNCwicGF0aCI6Ii8xMjE3MDk0MDkvMjg5Mjg2Mzk0LTBiNGFkYjMyLWJiYjUtNDk0ZC1hM2U1LTkxMzMzNTg4Mzc4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQxNjIwMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDJiMjBlYjViNWVkZDhjMjhmN2MxYzRlNmFiZTUwYmFjNjg3NjVkMTY2YzQwY2U3NGI5YmY4YTEyN2E2NTE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iPLf6qDhA9SmlIHLB9w3RUz6hB-uJFsei3gcqdwhvOY)
> 
> Everything is perfectly done. But I will recommend adding a tiny bit of fix as a closing btn in the window of placing the bid.

There was no close button in figma (and it is another ticket (approved, it is in dev)). But yeah, thank you for recomendation.

2023-12-09 16:35 UTC, SaidganiUsm submitted a review, later dismissed
Perfect

2023-12-09 16:40 UTC, SaidganiUsm approved these changes
Checked 😀

2023-12-09 18:48 UTC, otash8110 submitted a review, later dismissed

2023-12-13 12:45 UTC, TsvirkoNikita requested changes
Can you only show the "Withdraw" button if the last bid is the current user's bid?

2023-12-13 12:45 UTC, TsvirkoNikita commented on src/Auctionify.API/ClientApp/src/app/components/general/lot-profile/lot-profile.component.ts
> +        this.getBuyerRecentBidForLot().then((bidId) => {
What the reason to get recent bid for user each time when user click on Withdraw button, if you already have bids list in lotData?

2023-12-13 13:23 UTC, khasanrashidov commented on src/Auctionify.API/ClientApp/src/app/components/general/lot-profile/lot-profile.component.ts
> +        this.getBuyerRecentBidForLot().then((bidId) => {
I am taking each user's bid, to check if user can withdraw bid or not. There is a bidRemoved flag in user's bid, so when I get the user's bid, if that flag is true, the user cannot withdraw his bid. As we discussed the buyer can withdraw only once for the lot.

2023-12-13 13:56 UTC, TsvirkoNikita commented on src/Auctionify.API/ClientApp/src/app/components/general/lot-profile/lot-profile.component.ts
> +        this.getBuyerRecentBidForLot().then((bidId) => {
But you have a bids list inside the lotData object in your component, still don't understand

2023-12-13 14:40 UTC, TsvirkoNikita approved these changes

2023-12-13 15:55 UTC, TsvirkoNikita submitted a review, later dismissed

2023-12-13 17:23 UTC, SaidganiUsm approved these changes

2023-12-13 17:27 UTC, otash8110 approved these changes

2023-12-13 17:31 UTC, TsvirkoNikita approved these changes

2023-12-13 17:34 UTC, merged