[74] Reset Password (Backend)
U6D5T4/Auctionify pull request #8
Opened 2023-10-06 16:59 UTC by SaidganiUsm

### Where

[NL-74 Reset Password (Backend)](https://jjbcapital.atlassian.net/browse/NL-74)

### What

Resetting password

### How

Has been developed Reset password functionality using identity

### Affected Area

Auctionify.API
Auctionify.Application
Auctionify.Infrastructure

### PR Checklist

_Build_

- [x] Build Succeeded

_Unit Tests_

- [x] X Tests Passed, Y Ignored, Z Failed

2023-10-06 17:01 UTC, SaidganiUsm commented
There were some problems with commits, please pay attention to 2nd my commit.

https://github.com/U6D5T4/Auctionify/commit/f2af5da9884f69c65c85231de77c5eacb6bc6ed6

2023-10-08 20:38 UTC, TsvirkoNikita requested changes

2023-10-08 20:38 UTC, TsvirkoNikita commented on src/Auctionify.Infrastructure/Identity/SendGridEmailService.cs
> +			var client = new SendGridClient(apiKey);
apiKey is null here because you miss corresponding key in appsettings and miss any null check here, so application down with the exception on this line

2023-10-08 20:38 UTC, TsvirkoNikita commented on src/Auctionify.Infrastructure/Identity/IdentityService.cs
> +            await emailService.SendEmailAsync(email, "Rest Password", "<h1>Follow the instructions to reset your passwrod</h1>" +
Fix the typos

2023-10-08 20:38 UTC, TsvirkoNikita commented on src/Auctionify.Infrastructure/Identity/IdentityService.cs
> +                Message = "Reset password URL has benn sent to the eamil successfully"
And here

2023-10-09 17:37 UTC, SaidganiUsm commented
apiKey is inside the user secrets, and I will send it to you on Skype.

2023-10-10 07:34 UTC, TsvirkoNikita approved these changes

2023-10-10 13:13 UTC, TsvirkoNikita requested changes

2023-10-10 13:13 UTC, TsvirkoNikita commented on src/Auctionify.Infrastructure/ConfigureServices.cs
> +            services.AddIdentity<User, Role>(options =>
You duplicate Identity configuration

2023-10-10 13:52 UTC, merged