[40] - View active auctions (buyer)
U6D5T4/Auctionify pull request #88
Opened 2024-01-08 19:36 UTC by khasanrashidov

2024-01-14 10:32 UTC, otash8110 approved these changes

2024-01-15 06:31 UTC, SaidganiUsm submitted a review, later dismissed

2024-01-15 09:50 UTC, TsvirkoNikita requested changes

2024-01-15 09:50 UTC, TsvirkoNikita commented on src/Auctionify.API/ClientApp/src/app/components/buyer/dashboard/dashboard.component.ts
> +            console.log(this.lots);
Remove logs please

2024-01-15 09:50 UTC, TsvirkoNikita commented on src/Auctionify.API/ClientApp/src/app/components/buyer/dashboard/dashboard.component.ts
> +                this.priceColor = '#2b5293';
Move colors to constants with corresponded names

2024-01-15 09:50 UTC, TsvirkoNikita commented on src/Auctionify.Application/Features/Users/Queries/GetBuyerAuctions/GetBuyerAuctionsQuery.cs
> +				predicate: x => lotIds.Contains(x.Id),
Actually, you need to get only active auctions for that section. But as you already implemented some additional logic for showing auctions in other statuses, I could suggest adding sorting by status and show firstly active ones on this section.

2024-01-15 10:16 UTC, khasanrashidov commented on src/Auctionify.API/ClientApp/src/app/components/buyer/dashboard/dashboard.component.ts
> +            console.log(this.lots);
Removed

2024-01-15 10:39 UTC, khasanrashidov commented on src/Auctionify.Application/Features/Users/Queries/GetBuyerAuctions/GetBuyerAuctionsQuery.cs
> +				predicate: x => lotIds.Contains(x.Id),
Yeah, I agree (about only active auctions), that is more logical. But in design there was one auction in which the buyer already won, and I clarified that from you (that: Is active auction the one in which the buyer is participating and participated?) That's why I decided to include some other auctions statuses.

Got it!) I will implement sorting.

2024-01-15 11:07 UTC, khasanrashidov commented on src/Auctionify.Application/Features/Users/Queries/GetBuyerAuctions/GetBuyerAuctionsQuery.cs
> +				predicate: x => lotIds.Contains(x.Id),
I implemented sorting. First I am sorting (ordered by) active auctions, then sold auctions

2024-01-15 11:34 UTC, TsvirkoNikita approved these changes

2024-01-15 12:00 UTC, otash8110 approved these changes

2024-01-15 12:01 UTC, SaidganiUsm approved these changes

2024-01-15 12:01 UTC, merged