[150] - December Demo Bugs
U6D5T4/Auctionify pull request #90
Opened 2024-01-11 11:26 UTC by otash8110

Where
[NL-150 December Demo Bugs](https://jjbcapital.atlassian.net/browse/NL-150)

What
Fix bugs from december demo

How
Fix max price value to be limited to 100.000
Fix layouts of the whole application
Fix bugs with time display in the system

Affected Area
Auctionify.API.ClientApp
Auctionify.Application.Features
Auctionify.Infrastructure

PR Checklist
Build

 Build Succeeded
Unit Tests

[x] All 81 Tests Passed, 0 Ignored, 0 Failed

2024-01-11 11:39 UTC, SaidganiUsm submitted a review, later dismissed
Checked, great

2024-01-11 18:27 UTC, khasanrashidov submitted a review, later dismissed

2024-01-12 13:28 UTC, khasanrashidov submitted a review, later dismissed

2024-01-12 14:32 UTC, SaidganiUsm approved these changes, later dismissed

2024-01-16 08:27 UTC, khasanrashidov approved these changes, later dismissed

2024-01-16 10:14 UTC, TsvirkoNikita requested changes
What is the reason for using an empty General component instead of using a common css style for background?

2024-01-16 11:46 UTC, TsvirkoNikita approved these changes

2024-01-16 11:51 UTC, khasanrashidov approved these changes

2024-01-16 12:07 UTC, merged