[33] - View transactions history (buyer + seller)
U6D5T4/Auctionify pull request #91
Opened 2024-01-11 20:04 UTC by khasanrashidov

2024-01-14 10:34 UTC, otash8110 approved these changes

2024-01-15 11:38 UTC, khasanrashidov commented
Please don't check it right now @TsvirkoNikita , I will resolve the conflicts first (because before this I merged from other branches)

2024-01-15 11:39 UTC, khasanrashidov commented
I will let you know after I finish @TsvirkoNikita

2024-01-15 12:32 UTC, khasanrashidov commented
@TsvirkoNikita , now [33] is open for review

2024-01-16 12:08 UTC, otash8110 submitted a review, later dismissed

2024-01-18 20:43 UTC, khasanrashidov commented on src/Auctionify.API/ClientApp/src/app/components/general/transactions/transactions.component.html
> +                    <ng-container
fixed

2024-01-18 20:44 UTC, khasanrashidov commented on src/Auctionify.API/ClientApp/src/app/components/general/transactions/transactions.component.html
> +                    <ng-container
fixed responsiveness as well

2024-01-19 07:12 UTC, khasanrashidov commented on src/Auctionify.Application/Features/Users/Queries/GetTransactions/GetTransactionsUserQuery.cs
> +						lot.LotStatus.Name != AuctionStatus.Sold.ToString()
fixed

2024-01-19 12:19 UTC, TsvirkoNikita commented on src/Auctionify.Application/Features/Users/Queries/GetTransactions/GetTransactionsUserQuery.cs
> +						lot.LotStatus.Name != AuctionStatus.Sold.ToString()
Actually, I meant that the withdrawn status should be displayed in case when the buyer withdrawn exactly his last bid for that auction. And in this case we should show withdrawn status instead loss for that lot. At the moment, this status is displayed if the buyer returned any bid together with Loss status, which looks incorrect:
![image](https://github.com/U6D5T4/Auctionify/assets/35694505/c5c396f5-83fb-4477-87b6-b45525484a07)

2024-01-19 12:21 UTC, TsvirkoNikita requested changes
Please, check my reply in thread

2024-01-19 17:01 UTC, khasanrashidov commented on src/Auctionify.Application/Features/Users/Queries/GetTransactions/GetTransactionsUserQuery.cs
> +						lot.LotStatus.Name != AuctionStatus.Sold.ToString()
oh, now, I got you, thank you for noticing and remarks.
I fixed, now in case of the loss of the buyer in the auction (taking into account if he did bids and his last bid for the auction was withdrawn, the status will not be a loss but withdraw)

Here are two users, one did bid for the Lexus and withdrew it (and after that he didn't put any bids, and so the auction has ended and someone has one it):

![image](https://github.com/U6D5T4/Auctionify/assets/89701590/49bc51c1-0431-4761-b76d-44877a1c8b74)

other user who one that auction:

![image](https://github.com/U6D5T4/Auctionify/assets/89701590/4b8d5371-8ea6-492b-be94-9965d6bfd09b)

2024-01-20 06:04 UTC, khasanrashidov commented
Fixed

2024-01-21 08:44 UTC, SaidganiUsm approved these changes

2024-01-22 07:09 UTC, TsvirkoNikita approved these changes

2024-01-22 07:10 UTC, merged