[44 ,45] Leave a review (as a Buyer and as a Seller)
U6D5T4/Auctionify pull request #94
Opened 2024-01-17 09:14 UTC by SaidganiUsm

Where
[NL-45 Leave a review (as a Buyer)](https://jjbcapital.atlassian.net/browse/NL-45)
[NL-44 Leave a review (as a Seller)](https://jjbcapital.atlassian.net/browse/NL-44)

What
Users can rate a seller via purchased by him lot

How
Developed new logic for saving rates in db and validating the request (are user is a buyer of the current lot or not) 

Affected Area
Auctionify.API.ClientApp
Auctionify.Application.Features
Auctionify.Core
Auctionify.Infrastructure
Auctionify.UnitTests

PR Checklist
Build

 Build Succeeded
Unit Tests

[x] All 89 Tests Passed, 0 Ignored, 0 Failed

2024-01-28 19:43 UTC, otash8110 approved these changes

2024-01-29 08:50 UTC, khasanrashidov submitted a review, later dismissed

2024-01-31 12:40 UTC, khasanrashidov submitted a review, later dismissed

2024-02-01 07:43 UTC, Muhammad-gf requested changes

2024-02-01 07:43 UTC, Muhammad-gf commented on src/Auctionify.API/ClientApp/src/app/components/general/lot-profile/lot-profile.component.html
> +                currentUserId == lotData.seller?.id && lotData.lotStatus.id == 6
What does the number '6' mean? I would suggest turning it into a variable with meaningful naming.

2024-02-01 07:43 UTC, Muhammad-gf commented on src/Auctionify.API/ClientApp/src/app/components/general/rate-user/rate-user.component.html
> +        <ng-container *ngIf="isUserSeller(); else buyerTemplate">
I would suggest moving these ngif statements to the component.ts file. Making a specific variable for the img src and setting the path after checking isUserSeller().

2024-02-01 07:43 UTC, Muhammad-gf commented on src/Auctionify.API/ClientApp/src/app/components/general/rate-user/rate-user.component.html
> +                lotData && lotData.photosUrl?.[0]
I think you can use the above approach also here.

2024-02-01 07:43 UTC, Muhammad-gf commented on src/Auctionify.API/ClientApp/src/app/components/general/rate-user/rate-user.component.ts
> +            this.client.addRateToBuyer(rateData).subscribe(
Please, update the subscribe body by this article - https://rxjs.dev/deprecations/subscribe-arguments

2024-02-01 07:43 UTC, Muhammad-gf commented on src/Auctionify.API/ClientApp/src/app/components/general/rate-user/rate-user.component.ts
> +                (response) => {
You can make the body of the response as a separate method and use it twice.

2024-02-01 07:43 UTC, Muhammad-gf commented on src/Auctionify.API/ClientApp/src/app/components/general/rate-user/rate-user.component.ts
> +                (error) => {
The same here.

2024-02-01 07:43 UTC, Muhammad-gf commented on src/Auctionify.API/ClientApp/src/app/components/general/rate-user/rate-user.component.ts
> +    getUserProfileImage(src: string | undefined): string {
I think this method is not used anywhere, isn't it? You can remove it.

2024-02-01 19:11 UTC, SaidganiUsm commented on src/Auctionify.API/ClientApp/src/app/components/general/rate-user/rate-user.component.ts
> +    getUserProfileImage(src: string | undefined): string {
I'm using it in HTML file

2024-02-02 07:54 UTC, Muhammad-gf submitted a review, later dismissed

2024-02-04 15:17 UTC, khasanrashidov commented
fix your branch, it broke after merging the dev, because of new features, the dev has some significant and important changes:
![image](https://github.com/U6D5T4/Auctionify/assets/89701590/1d9e0728-7ce1-45e9-910e-00c527231e90)

2024-02-05 05:29 UTC, Muhammad-gf approved these changes

2024-02-05 06:43 UTC, khasanrashidov approved these changes

2024-02-05 06:44 UTC, merged