[26] View other users' profile
U6D5T4/Auctionify pull request #98
Opened 2024-01-21 18:29 UTC by SaidganiUsm

Where
[NL-26 View other users' profile](https://jjbcapital.atlassian.net/browse/NL-26)

What
Current users can view other users' profiles

How
Updated existing getById endpoint and added tests with front-end part

Affected Area
Auctionify.API.ClientApp
Auctionify.Application.Features
Auctionify.UnitTests

PR Checklist
Build

 Build Succeeded
Unit Tests

[x] All 84 Tests Passed, 0 Ignored, 0 Failed

2024-01-24 07:11 UTC, khasanrashidov requested changes

2024-01-24 07:11 UTC, khasanrashidov commented on src/Auctionify.Infrastructure/Data/Config/RateConfiguration.cs
> +				.OnDelete(DeleteBehavior.NoAction);
I cannot approve this right now, because the you changed the configuration and there is no migration for that.

2024-01-24 07:12 UTC, khasanrashidov commented on src/Auctionify.Infrastructure/Data/Config/RateConfiguration.cs
> +				.OnDelete(DeleteBehavior.NoAction);
It just cannot go to the dev (deployed just like that)

2024-01-28 19:44 UTC, otash8110 approved these changes

2024-01-29 08:08 UTC, khasanrashidov submitted a review, later dismissed

2024-01-29 08:12 UTC, otash8110 submitted a review, later dismissed

2024-01-30 09:44 UTC, TsvirkoNikita requested changes
Please, make the rating section more flexible. It can be moved down if it doesn't fit in the screen:
![image](https://github.com/U6D5T4/Auctionify/assets/35694505/1b6e1f57-c6e9-44ec-a46e-620f63481d0b)

2024-01-31 07:27 UTC, TsvirkoNikita requested changes
The "Show all comments" button still only opens the rating page with information about the current user, even if clicked from another user's page

2024-01-31 09:45 UTC, TsvirkoNikita approved these changes

2024-01-31 09:58 UTC, khasanrashidov approved these changes

2024-01-31 09:58 UTC, merged